/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.creditoproyectoprogra;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JPabloA
 */
public class PanelDebitos extends javax.swing.JPanel {

    /**
     * Creates new form PanelDebitos
     */
    public PanelDebitos() {
        initComponents();
        File archivo1;
        FileWriter escribir;
        PrintWriter linea;
        archivo1 = new File("C:\\Users\\JPabloA\\Desktop\\datosDebitos.txt");
        if (!archivo1.exists()){
            try{
                archivo1.createNewFile();
                escribir = new FileWriter(archivo1, true);
                linea = new PrintWriter(escribir);
                linea.close();
                escribir.close();
                
            }
            catch(IOException e){
                
            }
        }
        else{
            try{
                escribir = new FileWriter(archivo1, true);
                linea = new PrintWriter(escribir);
                linea.close();
                escribir.close();
            }
            catch(IOException e){
                
            }
        }
        File archivo2;
        archivo2 = new File("C:\\Users\\JPabloA\\Desktop\\datosMovimientos.txt");
        if (!archivo2.exists()){
            try{
                archivo2.createNewFile();
                escribir = new FileWriter(archivo2, true);
                linea = new PrintWriter(escribir);
                linea.close();
                escribir.close();
                
            }
            catch(IOException e){
                
            }
        }
        else{
            try{
                escribir = new FileWriter(archivo2, true);
                linea = new PrintWriter(escribir);
                linea.close();
                escribir.close();
            }
            catch(IOException e){
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTbusqueda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTidMovimiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTMonto = new javax.swing.JTextField();
        jComboTipo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboEstado = new javax.swing.JComboBox<>();
        jTBalanceIni = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTidProp = new javax.swing.JTextField();
        jTNumDebito = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Numero Debito", "Id Propietario", "Balance", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablaDatos);
        if (jTablaDatos.getColumnModel().getColumnCount() > 0) {
            jTablaDatos.getColumnModel().getColumn(0).setResizable(false);
            jTablaDatos.getColumnModel().getColumn(1).setResizable(false);
            jTablaDatos.getColumnModel().getColumn(2).setResizable(false);
            jTablaDatos.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Pantalla Panel de Debito");

        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Movimentos de Debito");

        jLabel4.setText("Ingrese el debito a buscar");

        jLabel9.setText("Agregar Movimiento a la cuenta de debito");

        jLabel10.setText("Id Movimiento");

        jTidMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidMovimientoActionPerformed(evt);
            }
        });

        jLabel11.setText("Monto");

        jTMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMontoActionPerformed(evt);
            }
        });

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposito", "Retiro" }));

        jLabel12.setText("Tipo");

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Agregar Credito");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel8.setText("Estado");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activa", "Inactiva", "Cancelada" }));
        jComboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEstadoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 120, -1));

        jTBalanceIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBalanceIniActionPerformed(evt);
            }
        });
        jPanel2.add(jTBalanceIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 120, -1));

        jLabel7.setText("Balance Inicial");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel6.setText("ID Propietario");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jTidProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidPropActionPerformed(evt);
            }
        });
        jPanel2.add(jTidProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, -1));
        jPanel2.add(jTNumDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 120, -1));

        jLabel5.setText("Numero Debito");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel13.setText("Agregar Cuenta Debito");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(12, 12, 12)
                                                .addComponent(jTidMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(54, 54, 54)
                                                .addComponent(jTMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(67, 67, 67)
                                                .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addComponent(jButton4))
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel9))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel2))
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jButton1))
                                            .addComponent(jLabel4)
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jTbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(48, 48, 48))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(jTbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(13, 13, 13)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTidMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jTMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jButton4)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String texto = jTbusqueda.getText();
        try{
            final BufferedReader hola = new BufferedReader(new FileReader("C:\\Users\\JPabloA\\Desktop\\datosDebitos.txt"));
            String line = "";
            boolean encontrado=false;
            while ((line = hola.readLine())!= null){
                System.out.println(line.toString());
                String[] datos = line.split(";");
                if(datos[0].equals(texto)){
                    DefaultTableModel model = (DefaultTableModel) jTablaDatos.getModel();
                    model.removeRow(0);
                    model.addRow(datos);
                    jTablaDatos.setModel(model);
                    jTbusqueda.setText("");
                    encontrado=true;
                    break;
                }
                
            }
            hola.close();
            if(encontrado==false){
                JOptionPane.showMessageDialog(null, "Debito no encontrado");
            }
            
 
        }
        catch(FileNotFoundException e){
            e.printStackTrace();
        }
        catch (IOException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTidMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidMovimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidMovimientoActionPerformed

    private void jTMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMontoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        File archivo;
        FileWriter escribir;
        PrintWriter linea;
        archivo = new File("C:\\Users\\JPabloA\\Desktop\\datosDebitos.txt");
        
        try{
            archivo.createNewFile();
            escribir = new FileWriter(archivo, true);
            linea = new PrintWriter(escribir);
            linea.print(jTNumDebito.getText()+";");
            linea.print(jTidProp.getText()+";");
            linea.print(jTBalanceIni.getText()+";");
            linea.print(jComboEstado.getSelectedItem().toString());
            linea.println("");
            linea.close();
            escribir.close();
            jTNumDebito.setText("");
            jTidProp.setText("");
            jTBalanceIni.setText("");
            jComboEstado.setSelectedIndex(1);
        }
        catch(IOException e){
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboEstadoActionPerformed

    private void jTBalanceIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBalanceIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBalanceIniActionPerformed

    private void jTidPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidPropActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         File archivo;
        FileWriter escribir;
        PrintWriter linea;
        archivo = new File("C:\\Users\\JPabloA\\Desktop\\datosMovimientos.txt");
        
        try{
            String datoBusqueda=jTbusqueda.getText();
            System.out.println(datoBusqueda);
            if(datoBusqueda!=""){
                if(BusquedaArchivo(datoBusqueda)==true){
                    archivo.createNewFile();
                    escribir = new FileWriter(archivo, true);
                    linea = new PrintWriter(escribir);
                    linea.print(jTidMovimiento.getText()+";");
                    linea.print(jTMonto.getText()+";");
                    linea.print(jComboTipo.getSelectedItem().toString());
                    linea.println("");
                    linea.close();
                    escribir.close();
                    jTidMovimiento.setText("");
                    jTMonto.setText("");
                    jComboTipo.setSelectedIndex(1);
                }
                else{
                     JOptionPane.showMessageDialog(null, "Debito no encontrado");
                     jTbusqueda.setText("");
                }
                
            }
            else{
              JOptionPane.showMessageDialog(null, "Espacio de Debito vacio");  
            }
            

        }
        catch(IOException e){
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    private boolean BusquedaArchivo(String i) throws FileNotFoundException, IOException{
        File archivo;
        FileWriter escribir;
        PrintWriter linea;
        archivo = new File("C:\\Users\\JPabloA\\Desktop\\datosDebitos.txt");
        final BufferedReader hola = new BufferedReader(new FileReader("C:\\Users\\JPabloA\\Desktop\\datosDebitos.txt"));
            String line = "";
        while((line = hola.readLine())!= null){
            String[] datos = line.split(";");
            System.out.println(i + " == " + datos[0]);
            if(i.equals(datos[0])){
                return true;
            }
                
        }
        return false;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboEstado;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBalanceIni;
    private javax.swing.JTextField jTMonto;
    private javax.swing.JTextField jTNumDebito;
    private javax.swing.JTable jTablaDatos;
    private javax.swing.JTextField jTbusqueda;
    private javax.swing.JTextField jTidMovimiento;
    private javax.swing.JTextField jTidProp;
    // End of variables declaration//GEN-END:variables
}
